apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: fitness-keyvault-secrets
  namespace: fitness-ns
spec:
  provider: azure
  secretObjects:
  - secretName: fitness-keyvault-secret
    type: Opaque
    data:
    - objectName: MONGODB-URI
      key: MONGODB_URI
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "cc3221de-e0d4-474d-aeff-e898b7cb50a7"
    keyvaultName: "surya-keyvault"
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    objects: |
      array:
        - |
          objectName: MONGODB-URI
          objectType: secret
